### ISSUE TITLE
Matrix Mapping Inefficiencies

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Org/ECP#17]
The process of mapping each x,y coordinate to its corresponding index in the matrix map is easily the worst part about this code base. The implementation is hacky, extremely hard to read and inefficient. There has to be a more intelligent way of doing this mapping.

**Comment by cSDes1gn** [comment]
@BrandonLucasZhu @StevenZhou2 Here is what we need:
We need a function that takes in an `(x,y,z)` tuple which define a coordinate in the cube and output a `Neuron` object corresponding to that coordinate. If the input coordinate is not within the cube space it should raise a `ValueError`. 

Keep in mind the function cannot assume a cube dimension size or use algebraic tricks to compute the expected number of edges. The goal is simply to find a cube object and represent it with a function that maps each neuron to an `(x,y,z)` coordinate tuple.

First you need to have a function to build the cube from a dictionary object defining all the `Neurons` in the `Pool` and their relationships to each other:
```python
pool = {<neuron0>: {<neuron1>:(rx,ry),
                    <neuron2>:(rx,ry),
                    ...
                    <neuron6>: (rx,ry)}
        <neuron1>: {...}
       ...
       }
```

Finally you need to develop a function which maps each of these neurons to a point in 3D space which allows it to take an input coordinate tuple `(x,y,z)` and map it to a specific `neuron`. From here I can optimize `SpatialCodec` to utilize this function to generate the corresponding bitmap.

**Comment by BrandonLucasZhu** [comment]
Closing this issue. Got a more clearer solution completed but, modifications will still be required in the long run.

**Comment by cSDes1gn** [comment]
yea thats fine, it was linked to the pull request anyways so It didnt have to be closed
